# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_auth_id', models.TextField(blank=True)),
                ('facebook_oauth_id', models.TextField(blank=True)),
                ('google_oauth_id', models.TextField(blank=True)),
                ('twitter_oauth_id', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
