# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetables', '0014_serving'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveSmallIntegerField(choices=[(5, 'EXCELLENT'), (4, 'GOOD'), (3, 'FAIR'), (2, 'POOR'), (1, 'TERRIBLE')])),
                ('comment', models.TextField(blank=True)),
                ('serving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.Serving')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('user', 'serving')]),
        ),
    ]
