# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('anonymity_id', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.PositiveSmallIntegerField(choices=[(5, 'EXCELLENT'), (4, 'GOOD'), (3, 'FAIR'), (2, 'POOR'), (1, 'TERRIBLE')])),
                ('comment', models.TextField(blank=True)),
                ('serving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.Serving')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
