# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20170709_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anonymity_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
