# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_anonymity_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([]),
        ),
    ]
