# -*- coding: utf-8 -*-
<<<<<<< 8ab5abfa9997904b5a75e3b6d4861427e44fd68a
# Generated by Django 1.9.7 on 2016-08-15 20:37
=======
# Generated by Django 1.9.7 on 2016-08-11 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            name='MealOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
