# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 22:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Example: appetizer, main course, dessert', max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='sequence_order',
            field=models.PositiveSmallIntegerField(help_text='The numerical order of the dishes for a meal option. E.g, 1 for appetizer, 2 for main course', unique=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='cycle_length',
            field=models.PositiveSmallIntegerField(help_text='Number of days in which the menu timetable is repeated after a period of time. E.g, A cycle length of 14 days (2 weeks) including the inactive weekdays like weekends after which the food schedule is repeated.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='ref_cycle_date',
            field=models.DateField(help_text='The reference date in time with which cycle day for any other following date can be computed. E.g, 1 if today is Sunday as first day of the cycle length. No need to always update this except the cycle changes.'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='ref_cycle_day',
            field=models.PositiveSmallIntegerField(help_text='The reference day (numerical value) in time with which cycle day for any other following date can be computed. E.g, 1 if today is Sunday as first day of the cycle length. No need to always update this except the cycle changes.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
