# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
