# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_auto_20160811_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealoption',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
