# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 19:59
from __future__ import unicode_literals

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0003_mealoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            bases=(common.mixins.SlugifyMixin, models.Model),
        ),
    ]
