# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('cycle_length', models.IntegerField()),
                ('current_cycle_day', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
