# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0005_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='current_cycle_day',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='cycle_length',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
