# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 09:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0005_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='current_cycle_day',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='cycle_length',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
