# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 14:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0007_auto_20160908_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('cycle_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.Meal')),
                ('meal_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.MealOption')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.Timetable')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set([('timetable', 'cycle_day', 'meal', 'meal_option')]),
        ),
    ]
