# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetables', '0007_auto_20160908_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_super', models.BooleanField()),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.Timetable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='admins',
            field=models.ManyToManyField(through='timetables.Admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
