# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0008_auto_20160913_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='slug',
            field=models.SlugField(editable=False, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mealoption',
            name='slug',
            field=models.SlugField(editable=False, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='weekday',
            name='slug',
            field=models.SlugField(editable=False, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='admin',
            unique_together=set([('user', 'timetable')]),
        ),
    ]
