# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 21:18
from __future__ import unicode_literals

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0010_auto_20160920_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('info', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(common.mixins.SlugifyMixin, models.Model),
        ),
    ]
