# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 13:16
from __future__ import unicode_literals

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0011_auto_20160923_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('info', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            bases=(common.mixins.SlugifyMixin, models.Model),
        ),
    ]
