# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0012_vendor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='TimetableManagement',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='admins',
            field=models.ManyToManyField(through='timetables.TimetableManagement', to=settings.AUTH_USER_MODEL),
        ),
    ]
