# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0015_auto_20161017_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sequence_order',
            field=models.PositiveSmallIntegerField(default=1, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='action',
            field=models.CharField(choices=[('no-meal', 'no meal will be served')], default='no-meal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetables.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='dish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetables.Dish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='cycle_day_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='vendor',
            field=models.ManyToManyField(to='timetables.Vendor'),
        ),
        migrations.AlterField(
            model_name='timetablemanagement',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set([('timetable', 'cycle_day', 'meal', 'course', 'dish')]),
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='meal_option',
        ),
        migrations.DeleteModel(
            name='MealOption',
        ),
    ]
