# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0017_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='sequence_order',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
