# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 14:30
from __future__ import unicode_literals

import app.timetables.utils
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0018_remove_uuid_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='public_id',
        ),
        migrations.AddField(
            model_name='serving',
            name='public_id',
            field=hashid_field.field.HashidField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', default=app.timetables.utils.timestamp_seconds, min_length=7, null=True),
        ),
        migrations.AddField(
            model_name='serving',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetables.Vendor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serving',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.MenuItem'),
        ),
        migrations.AlterUniqueTogether(
            name='serving',
            unique_together=set([('menu_item', 'vendor', 'date_served')]),
        ),
    ]
