# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 14:38
from __future__ import unicode_literals

from django.db import migrations

import app.timetables.utils


def populate_public_id_field(apps, schema_editor):
    Serving = apps.get_model('timetables', 'Serving')
    for row in Serving.objects.all():
        row.public_id = app.timetables.utils.timestamp_seconds()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0019_auto_20161110_1430'),
    ]

    operations = [
        migrations.RunPython(populate_public_id_field, reverse_code=migrations.RunPython.noop),
    ]
