# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 14:38
from __future__ import unicode_literals

import common.utils
from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0020_populate_hashid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serving',
            name='public_id',
            field=hashid_field.field.HashidField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', default=common.utils.timestamp_seconds, min_length=7, unique=True),
        ),
    ]
