# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0021_remove_hashid_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='start_date',
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.Timetable'),
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.Vendor'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='vendors',
            field=models.ManyToManyField(through='timetables.VendorService', to='timetables.Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorservice',
            unique_together=set([('timetable', 'vendor')]),
        ),
    ]
