# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0022_auto_20161114_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='cycle_day_updated',
            new_name='ref_cycle_date',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='current_cycle_day',
            new_name='ref_cycle_day',
        ),
    ]
