# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0023_auto_20161123_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServingAutoUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.Timetable')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.Vendor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='servingautoupdate',
            unique_together=set([('timetable', 'vendor', 'date')]),
        ),
    ]
