# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0025_remove_timetable_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='code',
        ),
    ]
