# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 13:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0026_remove_timetable_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='inactive_weekdays',
        ),
        migrations.AddField(
            model_name='timetable',
            name='inactive_weekdays',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.DeleteModel(
            name='Weekday',
        ),
    ]
